package edu.kit.ipd.pp.viper.model.parser;

public enum TokenType {
    COLON_MINUS, EQ, LESS, EQ_LESS, GREATER, GREATER_EQ, EQ_COLON_EQ, EQ_BS_EQ, EOF, DOT, COMMA, LP, RP, LB, RB, BAR, PLUS, MINUS, STAR, EXCLAMATION, IS, VARIABLE, IDENTIFIER, NUMBER
}
