image: "openjdk:8"

stages:
  - test
  - package
  
compile:
  stage: test
  script:
    - ./gradlew -w compileJava

jar:
  stage: package
  script:
    - ./gradlew -w jar
  artifacts:
    name: "Executable JAR for $CI_COMMIT_REF_NAME"
    paths:
      - ${CI_PROJECT_DIR}/build/libs/viper.jar
    when: always
    expire_in: 2 weeks

# Weitere Jobs einfach hier hinzufügen z.B. Checkstyle mit gradle
# (siehe https://docs.gradle.org/current/userguide/checkstyle_plugin.html):
#
#checkstyle:
#  stage: test
#  script:
#    - ./gradlew -w check