'set namespaceSeparator none
skinparam ranksep 50
'skinparam dpi 300
skinparam monochrome true
skinparam padding 2
skinparam classAttributeIconSize 0
skinparam groupInheritance 3
skinparam ParticipantPadding 30
hide circle
hide footbox
autoactivate on
